version: '3'
services:
  mongodb:
    image: mongo:3.6.1
    container_name: uv-mongodb
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
        - 27017:27017
    command: mongod
volumes:
  mongodb:
  mongodb_config: